steps:

#Obtem a imagem do docker-compose e executa o docker-compose especifico do cloud-build
- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

#Docker ps para verificar se os containers estão executando
- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

#Composer install (docker exec dentro do container app e depois composer install) 
- id: "Instando dependências com o composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']